### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Aluwuga** [JH220/discord-clearchatbot#5]
first i used /clear some other word 100 it said deleted 0 messages, then i kicked it and invited it again. Now i type /clear there are no such commands pls help
![1](https://user-images.githubusercontent.com/92209501/136654054-09570a05-522a-4bc9-b542-0bab65809256.PNG)

**Comment by nsde** [comment]
Hey, @Aluwuga 
make sure:
- The bot invite has `&scope=applications.commands` at the end. This is very important because it tells Discord that slash commands are being
- You and the bot have enough permissions, you need the `Use Slash Commands` permission in the channel you want to write the message to for launching a command! Of course, the bot needs to have the permission to view and send messages in your channel.
- Try the legacy, deprecated, classic command style; just like `cc clear`,  `cc help` and so on. This is a temporary solution, but let me know if this worked.

Hope I could help
:)

**Comment by nsde** [comment]
The instant invite link could make sure that the invite link *does* have slash command permissions.
